apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-script
data:
  init.sql: |
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'sentineldb') THEN
        CREATE DATABASE sentineldb;
      END IF;
    END
    $$;

    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sentineluser') THEN
        CREATE USER sentineluser WITH LOGIN PASSWORD 'sysadmin1';
      END IF;
    END
    $$;

    GRANT ALL PRIVILEGES ON DATABASE sentineldb TO sentineluser;
  
