apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
          resources:
            requests:
              memory: "256Mi"  # Minimum memory required
              cpu: "250m"      # Minimum CPU required
            limits:
              memory: "512Mi"  # Maximum memory allowed
              cpu: "500m"      # Maximum CPU allowed
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          # Health checks (probes)
          livenessProbe:
            exec:
              command:
                - pg_isready  # PostgreSQL readiness command
            initialDelaySeconds: 30  # Wait before checking
            periodSeconds: 10  # Check every 10 seconds
          readinessProbe:
            exec:
              command:
                - pg_isready
            initialDelaySeconds: 5  # Wait before checking
            periodSeconds: 10  # Check every 10 seconds
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the size as needed