apiVersion: v1
kind: Service
metadata:
  name: sentinel-postgres-service
spec:
  selector:
    app: sentinel-postgres   # <-- this must match the Postgres pod label
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP # Use ClusterIP for internal communication within the cluster

  
  # Optional: Uncomment the following line to create a headless service 
  #to allow direct access to the Pods without a load balancer.
  #clusterIP: None  # Headless service for internal communication
