apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: Y3JvbnVzZXI=  # base64 encoded
  postgres-password: c3lzYWRtaW4x  # base64 encoded
  postgres-db: Y3JvbmRi  # base64 encoded
  JWT_SECRET: aWt1ZDFVNnZ6YzhPaFZvTncwdmFkVEt0N01BMjBWbGs=
  database-url: cG9zdGdyZXM6Ly9jcm9udXNlcjpzeXN0ZW1hZG1pbjFAcG9zdGdyZXMtc2VydmljZTo1NDMyL2Nyb25kYg==  # base64
